/**
 * 프론트 정적 데이터(src/data/tools.ts) → 서버 시드(src/db/tools.seed.ts) 동기화 스크립트.
 * 실행: server/ 에서 `npm run sync:tools`
 *
 * 프론트 데이터가 바뀌면 이 스크립트를 다시 돌려 시드를 갱신하고 커밋한다.
 * (단일 진실 공급원은 프론트 tools.ts — 서버 시드는 파생물)
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { TOOLS } from "../../src/data/tools.ts";

const seeds = TOOLS.map((tool) => ({
  slug: tool.slug,
  name: tool.name,
  category: tool.category,
  badge: tool.badge ?? null,
  slogan: tool.slogan,
  priceInfo: tool.priceInfo,
  pricingDetails: tool.pricingDetails,
  difficulty: tool.difficulty,
  difficultyLevel: tool.difficultyLevel,
  editorialRating: tool.rating,
  features: tool.features,
  pros: tool.pros,
  cons: tool.cons,
  bestFor: tool.bestFor,
  aiIntegration: tool.aiIntegration,
  affiliateUrl: tool.affiliateUrl,
  alternatives: tool.alternatives,
  logoColor: tool.logoColor ?? null,
  logoTextColor: tool.logoTextColor ?? null,
}));

const content = `/**
 * AUTO-GENERATED by \`npm run sync:tools\` — 직접 수정하지 마세요.
 * 원본: ../../../src/data/tools.ts (프론트 정적 데이터)
 */
import type { ToolSeed } from "./seed-types.js";

export const TOOL_SEED: ToolSeed[] = ${JSON.stringify(seeds, null, 2)};
`;

const outPath = fileURLToPath(new URL("../src/db/tools.seed.ts", import.meta.url));
writeFileSync(outPath, content, "utf8");
console.log(`generated ${outPath} (${seeds.length} tools)`);
